---
- name: Debian Snort Configuration Module
  become: true
  hosts: localhost

  vars_files: ../vars/snort_vars.yml

  tasks:
    - name: Generate Copy snort.Conf
      local_action:
        module: copy
        src: "{{snort_loc}}"
        dest: "{{snort_copy_loc}}"
        owner: root
        group: root
        mode: '0644'

    - name: Configure Home_Net
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: 'ipvar HOME_NET any'
        line: "ipvar HOME_NET {{ ip_address | ipaddr('network/prefix') }}"
        state: present

    - name: Configure External Net
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: '#ipvar EXTERNAL_NET !$HOME_NET'
        line: 'ipvar EXTERNAL_NET !$HOME_NET'
        state: present

    - name: <Insert Name>
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: <Line to replace>
        line: <Line to insert>
        state: present

    - name: <Insert Name>
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: <Line to replace>
        line: <Line to insert>
        state: present

    - name: <Insert Name>
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: <Line to replace>
        line: <Line to insert>
        state: present

    - name: <Insert Name>
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: <Line to replace>
        line: <Line to insert>
        state: present

    - name: <Insert Name>
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: <Line to replace>
        line: <Line to insert>
        state: present

    - name: <Insert Name>
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: <Line to replace>
        line: <Line to insert>
        state: present

