---
- name: Debian Snort Configuration Module
  become: true
  hosts: localhost

  vars_files: ../vars/snort_vars.yml

  tasks:

    - name: Generate Copy snort.Conf
      local_action:
        module: copy
        src: "{{snort_loc}}"
        dest: "{{snort_copy_loc}}"

    - name: Configure Home_Net
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: 'ipvar HOME_NET any'
        line: "ipvar HOME_NET {{ ip_address | ipaddr('network/prefix') }}"
        state: present

    - name: Configure External Net
      lineinfile:
        path: "{{snort_copy_loc}}"
        regexp: '#ipvar EXTERNAL_NET !$HOME_NET'
        line: 'ipvar EXTERNAL_NET !$HOME_NET'
        state: present

    - name: Generate Copy snort.Conf - Redhat
      local_action:
        module: copy
        src: "{{snort_loc_rh}}"
        dest: "{{snort_copy_loc_rh}}"
        mode: "0777"

    - name: Configure Home_Net - Redhat
      lineinfile:
        path: "{{snort_copy_loc_rh}}"
        regexp: 'ipvar HOME_NET any'
        line: "ipvar HOME_NET {{ ip_address | ipaddr('network/prefix') }}"
        state: present

    - name: Configure External Net - Redhat
      lineinfile:
        path: "{{snort_copy_loc_rh}}"
        regexp: '#ipvar EXTERNAL_NET !$HOME_NET'
        line: 'ipvar EXTERNAL_NET !$HOME_NET'
        state: present

    - name: Configure Dynamic Location - Redhat
      lineinfile:
        path: "{{snort_copy_loc_rh}}"
        regexp: 'dynamicpreprocessor directory /usr/local/lib/snort_dynamicpreprocessor/'
        line: 'dynamicpreprocessor directory /usr/lib64/snort-2.9.19_dynamicpreprocessor/'
        state: present

    - name: Configure External Net - Redhat
      lineinfile:
        path: "{{snort_copy_loc_rh}}"
        regexp: 'dynamicengine /usr/local/lib/snort_dynamicengine/libsf_engine.so'
        line: 'dynamicengine /usr/lib64/snort-2.9.19_dynamicengine/libsf_engine.so'
        state: present

