---
- name: AWS Host Discovery
  hosts: localhost
  become: true

  vars_files:
    - ../src/vars/vars.yml
    - ../src/vars/VAULT.yml

  tasks:

    - name: Retrieve IP
      set_fact: 
         my_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: VPC
      amazon.aws.ec2_vpc_subnet_info:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "us-east-1"
      register: vpc_instance_fact

    - name: VPC Results
      set_fact:
        vpv_info: " {{ vpc_instance_fact | json_query('subnets[*].subnet_id') }} "

    - name: Gather EC2 Facts
      block:
      - name: Get instances facts
        ec2_instance_info:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          region: "us-east-1"
          filters:
            instance-state-name: "running"
        register: ec2_facts

    - name: Get Instance IPs
      set_fact:
        target_info: "{{ ec2_facts | json_query('instances[*].network_interfaces[*].{private_ip_address: private_ip_address, vpc_id: vpc_id}') }}"

    - name: Copy My_IP
      copy:
        content: "{{my_ip}}"
        dest: ../src/vars/target_info.tmp

    - name: Copy Ansible facts to a file
      lineinfile:
        path: ../src/vars/target_info.tmp
        line: " {{ target_info }} "
