---
- name: AWS Host Discovery
  hosts: localhost
  become: true

  vars_files:
    - ../src/vars/vars.yml

  tasks:
  
    - name: Retrieve IPv4 Subnet CIDR
      set_fact:
        mask_cidr: "{{ ip_mask | ipaddr('prefix') }}"

    - name: Set Addressing Facts
      set_fact:
        cidr: "{{ ip_address | ipaddr('network/prefix') }}"

    - name: Print
      debug:
        msg: "{{cidr}}"
