---
- name: NMAP Host Discovery
  hosts: localhost
  become: true

  vars_files:
    - ../src/vars/vars.yml

  tasks:
  
    - name: Retrieve IPv4 Subnet CIDR
      set_fact:
        mask_cidr: "{{ ip_mask | ipaddr('prefix') }}"

    - name: Set Addressing Facts
      set_fact:
        cidr: "{{ ip_address | ipaddr('network/prefix') }}"

    - name: NMAP Command
      become: true
      shell: "nmap -sn -PA22 -T5 -n 172.31.16.0/20 -oG - | awk '/Up$/{print$2}'"
      register: nmap

    - name: Set NMAP Target Facts
      set_fact:
        nmap_targets: "{{nmap.stdout}}"

    - name: Export Target ip
      local_action:
        module: copy
        content: "{{nmap_targets}}"
        dest: "../src/vars/nmap_targets.tmp"