---
- name: Install Snort
  hosts: targets
  become: true

  vars_files:
    - ../src/vars/snort_vars.yml

  tasks:

    - name: Install Snort-Specific Pre-reqs
      apt:
        name: "{{snort_ubuntu_prereq}}"
        state: present

    - name: Install Snort Packages
      script: ../Snort/snort_install.sh

    - name: Remove old snort.conf file 
      file:
        path: /etc/snort/snort.conf
        state: absent

    - name: Pull in Snort Configuration Template
      copy:
          src: ../src/vars/templates/snort.conf.tmp
          dest: /etc/snort/snort.conf