---
- hosts: Debian
  become: true
  tasks:

    - name: Install rsyslog
      apt:
        name: rsyslog
        state: present

    - name: Remove old rsyslog.conf file 
      file:
        path: /etc/rsyslog.conf
        state: absent

    - name: Pull in rsyslog configuration
      copy:
          src: ../../src/vars/templates/rsyslog_targets.conf
          dest: /etc/rsyslog.conf

    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted
        enabled: yes

- hosts: Redhat
  become: true
  tasks:

    - name: Install rsyslog
      yum:
        name: rsyslog
        state: present

    - name: Remove old rsyslog.conf file 
      file:
        path: /etc/rsyslog.conf
        state: absent

    - name: Pull in rsyslog configuration
      copy:
          src: ../../src/vars/templates/rsyslog_targets.conf
          dest: /etc/rsyslog.conf

    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted
        enabled: yes